GigHub/Models/Gig.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GigHub.Models
{
    public class Gig
    {
        public int Id { get; set; }

        [NotMapped]
        public string EncryptedGigId { get; set; }

        public ApplicationUser Artist { get; set; }

        [Required]
        public string ArtistId { get; set; }

        public DateTime DateTime { get; set; }

        [Required, StringLength(255)]
        public string Venue { get; set; }

        public Genre Genre { get; set; }

        [Required, Display(Name = "Genre")]
        public byte GenreId { get; set; }

        public string ImageUrl { get; set; }

        public bool IsCanceled { get; set; }
    }
}

GigHub/Controllers/GigsController.cs
using GigHub.Contracts;
using GigHub.Models;
using GigHub.Security;
using GigHub.Services;
using GigHub.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;

namespace GigHub.Controllers
{
    [Authorize]
    public class GigsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostEnvironment _hostEnvironment;
        private readonly IDataProtector _gigIdDataProtector;
        private readonly IDataProtector _imageValueDataProtector;
        private const string NoEncryption = "Select Encryption Type";
        private const string DataProtection = "1";
        private const string TripleDes = "2";
        private const string New = "New";
        private const string Modify = "Modify";
        private string _uniqueImageName = null;
        public GigsController(IUnitOfWork unitOfWork,
            UserManager<ApplicationUser> userManager, IHostEnvironment hostEnvironment,
            IDataProtectionProvider dataProtectionProvider, DataProtectionPurposeStrings dataProtectionPurposeStrings)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _hostEnvironment = hostEnvironment;
            _gigIdDataProtector = dataProtectionProvider.CreateProtector(dataProtectionPurposeStrings.GigIdRouteValue);
            _imageValueDataProtector = dataProtectionProvider.CreateProtector(dataProtectionPurposeStrings.ImageValue);
            
        }

        public IActionResult Create()
        {
            var model = new GigsFormViewModel
            {
                Genres = _unitOfWork.Genres.GetGenres(),
                EncryptionTechniques = GetEncryptionTechniques(), UserAction = New
            };

            return View("GigForm", model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(GigsFormViewModel model)
        {
            var key = _userManager.GetUserId(User); 
            var signature = User.Identity.Name; 

           // Check if the model state is valid with correct inputs from the user.
            if (!ModelState.IsValid)
                return ReturnEntryToUser(model);
            
            // Check to see if a photo is selected by the user.
            if (model.Photo != null)
            {
                if (ProcessImageBeforeSaving(model, signature, key, out var actionResult)) return actionResult;
            }

            CreateOrModifyAGig(model); // Create a gig object if adding a new gig or modify gig object if modifying a gig.
            _unitOfWork.Complete(); // Commit changes to the repository.

            // Redirect the user to the list of his/her upcoming gigs.
            return View("MyUpcomingGigs", GetMyUpcomingModel(key));
        }

        public IActionResult Edit(string id)
        {
            var gigId = Convert.ToInt32(_gigIdDataProtector.Unprotect(id));
            var gig = _unitOfWork.Gigs.FindGigById(gigId);

            //var model = new EditGigFormViewModel(gig)
            //{
            //    Genres = _unitOfWork.Genres.GetGenres()
            //};

            var model = new GigsFormViewModel()
            {
                Genres = _unitOfWork.Genres.GetGenres(), UserAction = Modify, EncryptionTechniques = GetEncryptionTechniques(), GigId = gig.Id,
                Venue = gig.Venue, Genre = gig.GenreId, Date = gig.DateTime.ToShortDateString(), Time = gig.DateTime.ToShortTimeString()
            };

            return View("GigForm", model);
        }
        
        [AllowAnonymous]
        public IActionResult AllUpcomingGigs()
        {
            return View(_unitOfWork.Gigs.GetUpcomingGigs()
                .Select(g =>
                {
                    g.EncryptedGigId = _gigIdDataProtector.Protect(g.Id.ToString());
                    return g;
                }));
        }

        public IActionResult MyUpcomingGigs()
        {
            ViewBag.Title = "My Upcoming Gigs";
            var artistId = _userManager.GetUserId(User);
            var model = GetMyUpcomingModel(artistId).Where(g => g.IsCanceled == false);

            return View(model);
        }

        public IActionResult Attending()
        {
            
            ViewBag.Title = "Gigs I'm Attending";
            var userId = _userManager.GetUserId(User);
            var attendances = _unitOfWork.Attendances.GigsIAmAttending(userId);
            

            return View("MyUpcomingGigs", attendances);
        }

        private bool ProcessImageBeforeSaving(GigsFormViewModel model, string signature, string key,
            out IActionResult actionResult)
        {
            using (var readStream = model.Photo.OpenReadStream())
            {
                var myImage = new Bitmap(Image.FromStream(readStream));
                var getEncodedTextInPicture =
                    Steganography.GetTextFromPicture(myImage); // Container for saving encoded text in picture

                // If the picture doesn't contains a text?
                if (string.IsNullOrEmpty(getEncodedTextInPicture))
                {
                    if (model.EncryptionType == NoEncryption) // The user chooses not to sign the picture.
                        SaveImage(myImage, out _uniqueImageName);
                    else
                        _uniqueImageName =
                            EncodeAndSaveImage(model, myImage, signature,
                                key); // User chooses to sign the picture
                }
                else // The picture contains text.
                {
                    var encryptionMethod = getEncodedTextInPicture.Substring(0, 1);
                    string decryptedSignature;

                    switch (encryptionMethod)
                    {
                        //Decrypt picture using Data Protection.
                        case DataProtection:
                        {
                            decryptedSignature = _imageValueDataProtector.Unprotect(getEncodedTextInPicture.Substring(1));
                            if (signature == decryptedSignature)
                                SaveImage(myImage, out _uniqueImageName);
                            else
                            {
                                actionResult = ReturnPrivacyWarning(model);
                                return true;
                            }

                            break;
                        }
                        //Decrypt picture using Triple DES
                        case TripleDes:
                        {
                            decryptedSignature = Security.TripleDes.Decrypt(getEncodedTextInPicture.Substring(1), key);
                            if (signature == decryptedSignature)
                                SaveImage(myImage, out _uniqueImageName);
                            else
                            {
                                actionResult = ReturnPrivacyWarning(model);
                                return true;
                            }

                            break;
                        }
                        default:
                        {
                            actionResult = ReturnPrivacyWarning(model);
                            return true;
                        }
                    }
                }
            }

            actionResult = null;
            return false;
        }

        private void CreateOrModifyAGig(GigsFormViewModel model)
        {
            if (model.UserAction == New)
            {
                // Create a new gig object.
                var gig = new Gig
                {
                    ArtistId = _userManager.GetUserId(User), DateTime = model.GetDateTime(), GenreId = model.Genre,
                    Venue = model.Venue, ImageUrl = _uniqueImageName
                };

                // Add gig object into gig collections.
                _unitOfWork.Gigs.AddAGig(gig);
            }
            else
            {
                // Modify a gig object.
                var gigInDb = _unitOfWork.Gigs.FindGigById(model.GigId);
                gigInDb.DateTime = model.GetDateTime();
                gigInDb.Venue = model.Venue;
                gigInDb.GenreId = model.Genre;
                if (model.Photo != null)
                {
                    if (gigInDb.ImageUrl != null)
                    {
                        var oldImage = Path.Combine(_hostEnvironment.ContentRootPath, @"wwwroot\images\", gigInDb.ImageUrl);
                        if (System.IO.File.Exists(oldImage))
                            System.IO.File.Delete(oldImage);
                    }
                    gigInDb.ImageUrl = _uniqueImageName;
                }
            }
        }

        private IEnumerable<Gig> GetMyUpcomingModel(string artistId)
        {
            return _unitOfWork.Gigs.GetMyUpcomingGigs(artistId)
                .Select(g =>
                {
                    g.EncryptedGigId = _gigIdDataProtector.Protect(g.Id.ToString());
                    return g;
                });
        }

        private IActionResult ReturnEntryToUser(GigsFormViewModel model)
        {
            model.Genres = _unitOfWork.Genres.GetGenres();
            model.EncryptionTechniques = GetEncryptionTechniques();

            return View("GigForm", model);
        }

        private IActionResult ReturnPrivacyWarning(GigsFormViewModel model)
        {
            ModelState.AddModelError("PrivacyWarning", "A copyright image detected, please replace image and try again.");

GigHub/Views/Gigs/AllUpcomingGigs.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<Gig>

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@{
    ViewData["Title"] = "Upcoming Gigs";
}

<div class="text-center">
    <h1 class="display-4">Find the next event You'll want to attend</h1>
</div>

<h6 class="display-5 voffset2">Upcoming Gigs</h6>

@if (Model.Any())
{
    <div class="card-deck">
        @foreach (var gig in Model)
        {
            var photoPath = "~/images/" + (gig.ImageUrl ?? "noimage.jpg");
            <div class="card m-3 card-arrangements">
                <img src=@photoPath class="card-img-top imageThumbnail" alt="@gig.Artist.Name" asp-append-version="true">
                <div class="card-body">
                    <div class="card-text"><strong><text>Artist: </text></strong>@gig.Artist.Name</div>
                    <div class="card-text"><strong><text>Genre: </text></strong>@gig.Genre.Name</div>
                    <div class="card-text"><strong><text>Venue: </text></strong>@gig.Venue</div>
                    <div class="card-text"><strong><text>Date: </text> </strong><em>@gig.DateTime.ToLongDateString()</em></div>
                    <div class="card-text"><strong><text>Time: </text> </strong><em>@gig.DateTime.ToShortTimeString()</em></div>
                </div>
                @if (gig.IsCanceled)
                {
                    <div class="card-footer">
                        <div class="text-muted text-center">
                            <div class="badge badge-pill badge-warning card-text"><strong><text>Notice: </text> </strong>This gig has been canceled</div>
                        </div>
                    </div>
                }
            </div>
        }

    </div>
}
else
{
    <div class="jumbotron">
        <h2 class="lead">No upcoming gigs in our records, click<a class="btn-link" asp-controller="Gigs" asp-action="Create"> here</a> to start adding a gig.</h2>
    </div>
}

GigHub/Views/Gigs/Create.cshtml
@model GigsFormViewModel

@{
    ViewData["Title"] = "Add a Gig";
}

<h2 class="display-5">Add a Gig</h2>

<div class="row">

    <form enctype="multipart/form-data" asp-controller="Gigs" asp-action="Create" role="form" method="post">

        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Venue"></label>
            <input type="text" asp-for="Venue" class="form-control col-md-9" autofocus="autofocus" />
            <span asp-validation-for="Venue" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Date"></label>
            <input type="text" asp-for="Date" class="form-control col-md-9" />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Time"></label>
            <input type="text" asp-for="Time" class="form-control col-md-9" />
            <span asp-validation-for="Time" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Genre"></label>
            <select asp-for="Genre" class="form-control col-md-9" asp-items="@(new SelectList(Model.Genres, "Id", "Name"))">
                <option>Select a Genre</option>
            </select>
            <span asp-validation-for="Genre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Photo"> Photo <span class="lead text-info">(optional)</span></label>
            <div class="custom-file col-md-9">
                <input asp-for="Photo" class="form-control custom-file-input" accept=".jpg, .jpeg" />
                <label class="custom-file-label">No Picture selected...</label>
            </div>
        </div>

        <div class="form-group">
            <label>Digitally Sign your Picture <span class="lead text-info">(optional)</span></label>
            <select asp-for="EncryptionType" class="form-control col-md-9" asp-items="@(new SelectList(Model.EncryptionTechniques,"Value","Text"))">
                <option>Select Encryption Type</option>
            </select>
        </div>


        <button class="btn btn-primary" type="submit">Save gig details &raquo;</button>


    </form>

</div>


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function ()
        {
            $('.custom-file-input').on('change', function ()
            {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });

        });
    </script>
}

GigHub/Views/Gigs/GigForm.cshtml
@model GigsFormViewModel

@{
    ViewData["Title"] = Model.UserAction + " Gig";
}

<h2 class="display-5">@Model.UserAction Gig</h2>

<div class="row">

    <form enctype="multipart/form-data" asp-controller="Gigs" asp-action="Create" role="form" method="post">

        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" asp-for="UserAction" />
        <input type="hidden" asp-for="GigId" />

        <div class="form-group">
            <label asp-for="Venue"></label>
            <input type="text" asp-for="Venue" class="form-control col-md-9" autofocus="autofocus" />
            <span asp-validation-for="Venue" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Date"></label>
            <input type="text" asp-for="Date" class="form-control col-md-9" placeholder="dd/mm/yyyy"/>
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Time"></label>
            <input type="text" asp-for="Time" class="form-control col-md-9" placeholder="HH:MM" />
            <span asp-validation-for="Time" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Genre"></label>
            <select asp-for="Genre" class="form-control col-md-9" asp-items="@(new SelectList(Model.Genres, "Id", "Name"))">
                <option>Select a Genre</option>
            </select>
            <span asp-validation-for="Genre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Photo"> Photo <span class="lead text-info">(optional)</span></label>
            <div class="custom-file col-md-9">
                <input asp-for="Photo" class="form-control custom-file-input" accept=".jpg, .jpeg" />
                <label class="custom-file-label">No Picture selected...</label>
            </div>
        </div>

        <div class="form-group">
            <label>Digitally Sign your Picture <span class="lead text-info">(optional)</span></label>
            <select asp-for="EncryptionType" class="form-control col-md-9" asp-items="@(new SelectList(Model.EncryptionTechniques,"Value","Text"))">
                <option>Select Encryption Type</option>
            </select>
        </div>


        <button class="btn btn-primary" type="submit">Save gig details &raquo;</button>
        <a asp-action="MyUpcomingGigs">Cancel</a>

    </form>

</div>


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function ()
        {
            $('.custom-file-input').on('change', function ()
            {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });

        });
    </script>
}

GigHub/Views/Gigs/MyUpcomingGigs.cshtml
@model IEnumerable<Gig>


@{
    ViewData["Title"] = ViewBag.Title;
}

<div class="text-center">
    <h1 class="display-4">Find the next event You'll want to attend</h1>
</div>

<h6 class="display-5 voffset2">My Upcoming Gigs</h6>

@if (Model.Any())
{
<div class="card-deck">
    @foreach (var gig in Model)
    {
        var photoPath = "~/images/" + (gig.ImageUrl ?? "noimage.jpg");
        <div class="card m-3 card-arrangements">
            <img src=@photoPath class="card-img-top imageThumbnail" alt="@gig.Artist.Name" asp-append-version="true">
            <div class="card-body">
                <div class="card-text"><strong><text>Genre: </text></strong>@gig.Genre.Name</div>
                <div class="card-text"><strong><text>Venue: </text></strong>@gig.Venue</div>
                <div class="card-text"><strong><text>Date: </text> </strong><em>@gig.DateTime.ToLongDateString()</em></div>
                <div class="card-text"><strong><text>Time: </text> </strong><em>@gig.DateTime.ToShortTimeString()</em></div>
            </div>
            <div class="card-footer" style="font-weight: bolder;">
                <div class="text-muted text-center">
                    <a asp-controller="Gigs" asp-action="Edit" asp-route-id="@gig.EncryptedGigId">Edit</a> |
                    <a class="js-cancel-gig" data-gig-id="@gig.EncryptedGigId" href="#">Delete Event</a>
                </div>
            </div>
        </div>
       
    }

</div>
}
else
{
    <div class="jumbotron">
        <h2 class="lead">You have no upcoming gig in our records, click<a class="btn-link" asp-controller="Gigs" asp-action="Create"> here</a> to start adding a gig.</h2>
    </div>

}

@section Scripts
{
    <script>
        $(document).ready(function ()
        {
            $(".js-cancel-gig").click(function (e) {
                var link = $(e.target);
                var dialog = bootbox.dialog({
                    title: 'Confirm delete operation',
                    message: "<p>Are you sure you want to cancel this event.</p>",
                    size: 'large',
                    buttons: {
                        cancel: {
                            label: "No",
                            className: 'btn-success',
                            callback: function() {
                                bootbox.hideAll();
                            }
                            
                        },
                        ok: {
                            label: "Yes",
                            className: 'btn-danger',
                            callback: function() {
                                $.ajax({
                                    url:"/api/gigs/" + link.attr("data-gig-id"),
                                    method: "DELETE"
                                }).done(function() {
                                    link.parents("div.card").fadeOut(function() {
                                        $(this).remove();
                                    }).fail(function() {
                                        alert("Something went wrong");
                                    });
                                });
                            }
                        }
                    }
                });
            });
        });
    </script>
}